### ISSUE TITLE
Metric time is 1 hour wrong

### ISSUE THREAD

**Issue by itsRems** [CastawayLabs/cachet-monitor#102]
Hi.
I've recently installed cachet-monitor and tried to run some tests.
Everything seemed to be right until I run into a little problem: every time my metric is updated, the time of the metric point is 1 hour late. I ran the tests at 7:50PM and eventhough the timezone of Cachet is set up correctly, the metrics showed the date sent a 7:50PM at 6:50PM.
Can this be a problem with this package itself or a missconfiguration?
Let me know if you need any information/config files.

**Comment by BillyAB** [comment]
I'm having the same issue, has anyone got to the bottom of this?

**Comment by rsiebertdev** [comment]
I know, one year later but I thought I would share how I fixed this. Your system and MySQL/Apache2 (Or Nginx) has to be the correct time zone, I managed to figure this out my self. Even if Cachet has the same time zone, and that the Cachet Monitor is using the correct time zone, chances are that your MySQL or Apache2/Nginx services aren't on the correct time zones.
