### ISSUE TITLE
Be able to configure the frequency of checks

### ISSUE THREAD

**Issue by athieriot** [CastawayLabs/cachet-monitor#12]
Currently cachet-monitor seems to check the configured URLs every seconds.
In some scenario it would probably be ok to do that only every few minutes.

It would be nice to be able to configure the frequency either in the config file, either by ENV variable.

However, it works just fine like that so it would just be a nice to have.

**Comment by matejkramny** [comment]
That is in PR #10

There may be issues with the analysis part as mentioned in the comments if the frequency is too low.

**Comment by athieriot** [comment]
Erf. Haven't seen this -_-

Happy to wait until you are happy (or help if needed)

**Comment by matejkramny** [comment]
I have no issues with merging it, but it'll need work to adjust the analytics system.
