### ISSUE TITLE
Could not log data point!

### ISSUE THREAD

**Issue by igorissen** [CastawayLabs/cachet-monitor#13]
Hi,

I've just installed CachetHQ and your plugin, and it works well but I'm still getting this message :

```
2015/06/04 14:29:31 /home/ubuntu/.gvm/pkgsets/go1.4.2/global/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:68: https://api.mydomain.com/ping 0.00% Down at 1433420971. Threshold: 80.00%
2015/06/04 14:29:31 /home/ubuntu/.gvm/pkgsets/go1.4.2/global/src/github.com/castawaylabs/cachet-monitor/cachet/metrics.go:20: Could not log data point!
<nil>
```

When I look at the [CachetHQ documentation](https://docs.cachethq.io/) and you request, POST /metrics/{id}/points does not exists (GET and DELETE only). Did I need to use a specific version of CachetHQ with your plugin ?

**Comment by craftbyte** [comment]
Seems like the function is just not documented. You can see the function definition here: https://github.com/cachethq/Cachet/blob/dd8fc6020901e18894142d104a94d996220e10d5/app/Http/Routes/ApiRoutes.php#L55

**Comment by matejkramny** [comment]
You should be using the latest version (v1?).

Can you try again with the latest updates?

Thanks

**Comment by JC1738** [comment]
Also get the same problem:  

2015/10/28 00:23:05 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:84: https://pathtomysite 0.00% Down at 1445991785. Threshold: 80.00%
2015/10/28 00:23:05 /go/src/github.com/castawaylabs/cachet-monitor/cachet/metrics.go:20: Could not log data point!
<nil>

I verified that in the docker container that I can curl the path to my site and I do receive 200 status response.

I tried the latest docker image in repository as well as checked out and built my own.

**Comment by Dids** [comment]
Make sure your API url ends with /api/v1.

**Comment by matejkramny** [comment]
@igorissen let us know if this is still an issue.
