### ISSUE TITLE
can't load package: package github.com/castawaylabs/cachet-monitor

### ISSUE THREAD

**Issue by f0o** [CastawayLabs/cachet-monitor#19]
Ok total GO Noob here.

I'm on upstream debian jessie and install `golang`.

Issuing `go install github.com/castawaylabs/cachet-monitor` returns:

```
can't load package: package github.com/castawaylabs/cachet-monitor: cannot find package "github.com/castawaylabs/cachet-monitor" in any of:
        /usr/lib/go/src/pkg/github.com/castawaylabs/cachet-monitor (from $GOROOT)
        ($GOPATH not set)
```

I've cloned the repo:
- run it inside it, same effect.
- run it outside it, pointing to it's path, same effect.
- moved the repo to /usr/lib/go/src/pkg/github.com/castawaylabs/cachet-monitor, different error but yet error

What's the gist about this?

**Comment by matejkramny** [comment]
The issue as the log posted says, `$GOPATH not set`.

Seems like you havent done anything with go yet, so:

```
mkdir /go
export GOPATH=/go
go install github.com/castawaylabs/cachet-monitor
# now installed in /go/bin/cachet-monitor
```

**Comment by f0o** [comment]
Thanks now I get

```
# github.com/castawaylabs/cachet-monitor
/usr/lib/go/src/github.com/castawaylabs/cachet-monitor/main.go:24: syntax error: unexpected range, expecting {
/usr/lib/go/src/github.com/castawaylabs/cachet-monitor/main.go:28: syntax error: unexpected }
```

At least a step in the right direction haha

**Comment by f0o** [comment]
Replacing line 24 of main.go with `for _ = range ticker.C {` like in https://github.com/CastawayLabs/cachet-monitor/commit/d421b35e9be1900399026fe1f16e3e482d085615#diff-7ddfb3e035b42cd70649cc33393fe32c solved it.

Is this a bug? Is my Go outdated?

**Comment by matejkramny** [comment]
It might be a bug. Which go are you running?

**Comment by f0o** [comment]
Sorry for late answer, the mail got under a flood of other GH issues hehe

Here my version:

``` shell
# go version
go version go1.3.3 linux/amd64
```

//Edit after that addition mentioned above, the monitor has been running great. Cachet is now having trouble keeping up with the data ;)

**Comment by matejkramny** [comment]
Right I think you need to either compile the binary on a system where you can have go1.4 or 1.5 or install the relevant version on your machine.

Cross-compiling is very easy (at least on 1.5) and it could be possibly provided in the Releases section in the future.

go1.3 might not support the shorthand syntax which you had to fix manually (amongst other things!)

**Comment by f0o** [comment]
Fair enough :)

Not sure how Go's release cycles are, but perhaps put that in the readme if I'm not on a terribly outdated version (debian is slow ;)

**Comment by matejkramny** [comment]
yeah its debian :P. But the thing is, you dont even need Go installed for this to work on your linux...

**Comment by f0o** [comment]
Oh thats decent, I'll get a newer version on my gentoo laptop and push it up to the servers and see if it goes any better :)

Anyways thanks a lot for the chat, I'll close this invalid issue ;)

**Comment by matejkramny** [comment]
no probs
