### ISSUE TITLE
unknown field ‘Timeout’ in ‘http.Client’

### ISSUE THREAD

**Issue by elbundi** [CastawayLabs/cachet-monitor#21]
$GOROOT is set, GOPATH is set, yet when we "go install ..." we ge the following error:

cachet-monitor/cachet/monitor.go:47:3: error: unknown field ‘Timeout’ in ‘http.Client’
   Timeout: timeout,
   ^

We're running Ubuntu 14.04.3 lts
and we've pulled the latest file of cachet.monitor

**Comment by matejkramny** [comment]
What is your go version?

**Comment by elbundi** [comment]
go1.2.1

**Comment by DarkSeraphim** [comment]
Timeout was added the release right after 1.2.1

**Comment by matejkramny** [comment]
Please update your go version, or cross-compile on another machine for your server
