### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by elbundi** [CastawayLabs/cachet-monitor#22]
Docker Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Ran through setup and errors out at step 3: cachet-monitor -c https://raw.githubusercontent.com/CastawayLabs/cachet-monitor/master/example.config.json

error received:
cachet-monitor: command not found

**Comment by matejkramny** [comment]
What's your `$PATH`?

It should contain `$GOPATH/bin` equiv (eg `/go/bin/`). You can alternatively move it:

`cp $GOPATH/bin/cachet-monitor /usr/local/bin`

**Comment by elbundi** [comment]
we had a hard time with docker. we had to remove /var/lib/docker first and rm -rf wasn't enough, 

this worked
$ umount -l $(grep 'aufs' /proc/mounts | awk '{print$2}' | sort -r)

re installed docker to get us the latest cachet-monitor, then

$ export GOPATH=/var/lib/docker/aufs/diff/74b95308536c367e80977b211b673d6f9d3ecc8d0eb312d821a750a2a66dab66/go/

this worked fine, no error:      $ go install github.com/castawaylabs/cachet-monitor

then step 3
$ cachet-monitor -c https://raw.githubusercontent.com/CastawayLabs/cachet-monitor/master/example.config.json

$ cachet-monitor: command not found

**Comment by matejkramny** [comment]
Try the following (code at the bottom), although i think you're overcomplicating things. The docker example is to run cachet-monitor as a docker container. It looks like you're running some docker container and then hacking around it.

```
/var/lib/docker/aufs/diff/74b95308536c367e80977b211b673d6f9d3ecc8d0eb312d821a750a2a66dab66/go/bin/cachet-monitor -c https://raw.githubusercontent.com/CastawayLabs/cachet-monitor/master/example.config.json
```

**Comment by elbundi** [comment]
That's exactly what we did, hacked around it.
Anyway,  your code worked. You can close this issue

**Comment by Echobob** [comment]
Closed by @elbundi
