### ISSUE TITLE
No Matter What We Try

### ISSUE THREAD

**Issue by unfriendly** [CastawayLabs/cachet-monitor#23]
It keeps saying the service we are pinging is down??

https://ping.proxy-bite.com/ping

2016/01/15 20:50:48 /usr/lib/golang/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:84: https://ping.proxy-bite.com/ping 100.00% Down at 1452912648. Threshold: 80.00%

**Comment by craftbyte** [comment]
Looks to me like you forgot a dot before com

**Comment by Echobob** [comment]
No that's just github stripping the periods out from the email
notification. If you look at it on github, the url is valid.

**Comment by craftbyte** [comment]
@Conciliare Could you please attach your config to the issue, you can omit the API keys

**Comment by unfriendly** [comment]
{
  "api_url": "https://random.random.com/api/v1",
  "api_token": "RandomString",
  "interval": 5,
  "monitors": [
    {
      "name": "ProxyBite Network",
      "url": "https://ping.proxy-bite.com/ping",
      "metric_id": 1,
      "threshold": 80,
      "component_id": null,
      "expected_status_code": 304,
      "strict_tls": true
    }
  ],
  "insecure_api": false
}

**Comment by unfriendly** [comment]
I am using a custom NGinx cdn configuration so it does not post a 200 as a normal web page!

**Comment by craftbyte** [comment]
Try setting the status to 200. I think the library counts redirects.

Here is the response I get for a GET request to the URL:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: max-age=2592000, public
Connection: keep-alive
Content-Length: 19
Date: Sat, 16 Jan 2016 09:24:55 GMT
Expires: Mon, 15 Feb 2016 04:57:38 GMT
Last-Modified: Sat, 16 Jan 2016 02:43:01 GMT
Server: Sucuri/Cloudproxy
Vary: User-Agent
X-Accel-Version: 0.01
X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
X-WebKit-CSP: default-src 'self'
X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block

{ "data: "Pong!" }
```

**Comment by unfriendly** [comment]
Just set it, but same result..

**Comment by matejkramny** [comment]
@Conciliare nginx sends 304 if it thinks the client has a cached version. In the case of this project, it doesn't send any cache headers and therefore nginx should always respond with 200.

Your config suggests that you expect a 304 but it it is really a 200, therefore it marks it as unsuccessful.
