### ISSUE TITLE
Possible to install via go cli?

### ISSUE THREAD

**Issue by lifehome** [CastawayLabs/cachet-monitor#32]
Is it possible to install via `go install`? Can't really think of why downloading a prebuilt package while go is really fast enough to build on every machine.

**Comment by matejkramny** [comment]
Its built with sql migrations & public files (html, css, js) all bundled into the binary. It isn't done with `go install` unless it was checked into git.

Its using `go-bindata` to package it

**Comment by matejkramny** [comment]
It'll need some restructuring to be able to do installs without pre-packaging..

**Comment by matejkramny** [comment]
Ignore the above comment. I got confused between projects.

You can install via `go install` but you have to install the `cli` package
