### ISSUE TITLE
Adding basic access authentication

### ISSUE THREAD

**Issue by khelll** [CastawayLabs/cachet-monitor#33]
Is it doable to add support for websites using basic access authentication?. This is goint to be helpful for web services as well.
Bascially, we need to add username/password per monitored component:

``` json
{
 //other settings,
"username": "someone",
"password": "somepass"
}
```

**Comment by matejkramny** [comment]
It is an extra HTTP header (i think `Authorization: Basic <hash>`)

We could add support for configuring additional http headers

**Comment by yannickoo** [comment]
You can simply add the username and password to the URL
➡️ `https://someone:somepass@example.com`.
