### ISSUE TITLE
Support for modified or localized incident text

### ISSUE THREAD

**Issue by khelll** [CastawayLabs/cachet-monitor#34]
Since Cachet supports different locales, is it doable to have the text of the reported incident localized somehow? This can be solved also if a one can change the text itself via configuration for example.

**Comment by matejkramny** [comment]
Yeah we should provide customisable messages. I think `text/template` will be handy for this, you'll be able to plug in custom variables as needed.

I wonder if the API error messages are in the setup locale.

**Comment by matejkramny** [comment]
Released as part of v3.
