### ISSUE TITLE
100% CPU when viewing graph

### ISSUE THREAD

**Issue by alexcroox** [CastawayLabs/cachet-monitor#36]
Single metrics, only 3 components. As soon as I enable the metrics graph via cachet-monitor the CPU hits 100% for every page view for a good 60 seconds. If I disable the single metrics there is never any real load on the server rendering the page.

Am I doing something wrong?

Config:

```
{
  "api_url": "http://xx.xx.com/api/v1",
  "api_token": "xxx",
  "interval": 5,
  "monitors": [
    {
      "name": "xx Website",
      "url": "https://xx.com/apply",
      "metric_id": 2,
      "threshold": 80,
      "component_id": 1,
      "expected_status_code": 200,
      "strict_tls": true
    }
  ],
  "insecure_api": false
}

```

**Comment by matejkramny** [comment]
Is your cachet installation up to date?

They recently upgraded the way graphs are rendered. We experienced this graph CPU issue a long time ago.
