### ISSUE TITLE
How to properly install and run cachet-monitor

### ISSUE THREAD

**Issue by apssupport** [CastawayLabs/cachet-monitor#37]
Good afternoon,

I've searched and read through the documentation as well as searched online for instructions, but I am not sure if I installed it properly. I did a git clone and git checkout, created a new cachet-monitor.config.json but when trying to run it, I get "cachet-monitor: command not found"

Please advise if you can.

**Comment by matejkramny** [comment]
Hi,

You should follow the [install](https://github.com/CastawayLabs/cachet-monitor#installation) instructions

**Comment by apssupport** [comment]
Hello,

Thanks for quick reply. I did follow install instructions. I downloaded
binary, create config and tried to run it like it says but I get command
not found. I just need help with the actual "installation" if it even needs
to be installed.

On Sun, Jun 19, 2016 at 4:19 PM, Matej Kramny notifications@github.com
wrote:

> Hi,
> 
> You should follow the install
> https://github.com/CastawayLabs/cachet-monitor#installation instructions
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/CastawayLabs/cachet-monitor/issues/37#issuecomment-227018082,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASvmsz516mk_2_6d_CSmephejwe2uOq6ks5qNaQ3gaJpZM4I5O0u
> .

## 

_Evangelos Liandrakis_

**Comment by matejkramny** [comment]
I see, sorry.

You should either:

1) configure your `$PATH` to include the folder you downloaded `cachet-monitor` to
2) move the binary to `/usr/bin/cachet-monitor`

Then it will be found.

Hope this helps!

**Comment by apssupport** [comment]
Definitely appreciate you helping me out with this (probably something so simple) yet I am not getting it to work. Followed your advice above and it is still saying the same.

![screen shot 2016-06-19 at 4 39 29 pm](https://cloud.githubusercontent.com/assets/19654323/16179722/70dc0c9c-363c-11e6-9291-c673fd5ff5ac.png)

**Comment by apssupport** [comment]
Hi ticket #26 helped with installing cachet-monitor. The go get -d github.com/castawaylabs/cachet-monitor was the missing link to getting it installed.

**Comment by apssupport** [comment]
Still getting the command not found error. Below is the output of $PATH

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin:/go/bin:/go/bin/:/usr/local/go/bin

Cachet-monitor was installed after following ticket #26 and it was automatically placed in its own directory 

/go/src/github.com/castawaylabs/cachet-monitor

Created the config /etc/cachet-monitor.config.json and no matter what and how I run it, I get command not found.

**Comment by matejkramny** [comment]
Cachet-monitor is not `go install`able.

Follow this:
1. `curl -L <download-link> > /usr/local/bin/cachet-monitor`
2. `cachet-monitor -c ....`

**Comment by apssupport** [comment]
That was it! Thank you so much, especially for helping out on a Sunday!

**Comment by matejkramny** [comment]
No worries. Its not a Sunday for me ;)

**Comment by apssupport** [comment]
Well, have a great new week then. Thank you again!
