### ISSUE TITLE
Any plans for other checks?

### ISSUE THREAD

**Issue by tuxis-ie** [CastawayLabs/cachet-monitor#38]
I'l like to use this great tool for other stuff than HTTP. Any plans to make plugins possible for eg DNS probing?

**Comment by matejkramny** [comment]
Thats definitely possible. Lets think about it :)

**Comment by 0xGabrielel** [comment]
Surely a PING one would be so handly... Can you please implement it @matejkramny ?
Thanks

**Comment by therapy-lf** [comment]
I need to check my socks-proxy port and it doesn't understand http methods, so it would be great if you implement simple tcp probing.

**Comment by nico01f** [comment]
+1

**Comment by NHellFire** [comment]
A raw socket check (with TLS support) that allows specifying the request and expected response would cover quite a few services.

**Comment by matejkramny** [comment]
Implemented a DNS check.
The interface is very extensible now and other checks can be written very easily. I think i'll leave it up to the community for now!

https://github.com/CastawayLabs/cachet-monitor/releases/tag/v3.0
