### ISSUE TITLE
After a ended outage the status of the service should be the same as before the incident.

### ISSUE THREAD

**Issue by sapk** [CastawayLabs/cachet-monitor#42]
For example on a system where the website is manually mark "Performance Issues" if cachet monitor detect outage it will mark it as "... outage" at the end of the probleme cachetmonitor will put the service as "Operational". 
I think it should be better if we revert back to the state before the incident.

**Comment by sapk** [comment]
A solution could be to indicate the status of the service before the outage in the incident created. And based on that information when closing the incident revert back to this state ?

**Comment by matejkramny** [comment]
The program does this, if it finds a component which is already in partial outage it makes it major outage.
