### ISSUE TITLE
Multiple Monitors

### ISSUE THREAD

**Issue by thetechgy** [CastawayLabs/cachet-monitor#44]
It looks like it's possible to configure multiple monitors from the config file, but I must have something wrong in my syntax (I'm guessing it's brackets). Can you add an example with a config for multiple monitors?

**Comment by therapy-lf** [comment]
@thetechgy It works for me:

{
  "api_url": "your_api_url",
  "api_token": "token",
  "insecure_api": false,
  "monitors": [
    {
      "name": "Common name 1",
      "url":  "http://example.com",
      "threshold": 80,
      "metric_id": 1,
     "component_id": 1,
      "interval": 60,
      "timeout": 5,
      "expected_status_code": 200,
      "strict_tls": false
    },
    {
      "name": "Common name 2",
      "url":  "http://example2.com",
      "threshold": 80,
      "metric_id": 2,
     "component_id": 2,
      "interval": 60,
      "timeout": 5,
      "expected_status_code": 200,
      "strict_tls": false
    }
  ],
  "system_name": "us-bot",
  "log_path": "/var/log/cachet-monitor.log"
}

**Comment by thetechgy** [comment]
@therapy-lf, that works perfectly - I was missing the comma between the components. Thanks!
