### ISSUE TITLE
do i run multiple instances of cachet-monitor for each target sys

### ISSUE THREAD

**Issue by moodhair** [CastawayLabs/cachet-monitor#45]
Being new to Linux and go this might seem like a moronic question.  My question is if I want to monitor the health of 10 systems - do I run a separate instance of cachet-monitor for each system in a cron job?  Also, would anyone be willing to share some insight on what metrics they track and how?  Trying to learn a little best practice as I move along.  My implementation is very simple and is for an internal farm of systems (10 or you may have guessed that already) and I just need a simple status page.  Cachet seems to fit the bill and this little gem seems to be part of the answer.  Just having a tough time making heads or tails of all of the info on the web that always seems to be off just a smidge... Any ways - back to the question:  a separate instance for each component/metric?

**Comment by moodhair** [comment]
i guess that was a dumb question - sorry

**Comment by matejkramny** [comment]
Hi, not a dumb question.

You can have multiple components, and this software is designed to run as a daemon. You can however scale it to other instances and perhaps in different data centers / geo areas.
