### ISSUE TITLE
API response time

### ISSUE THREAD

**Issue by mkok1019** [CastawayLabs/cachet-monitor#48]
Hey, guys, @matejkramny 

I've just installed cachet-monitor and check the response time of my api.
It says, 203.93ms, but when I ping the api url in console, it only takes 20ms,

Is this something like a bug?

**Comment by matejkramny** [comment]
not quite, because cachet pings the API which is not the same ping as with the `ping` command.

`ping` sends ICMP requests and pings the server.

cachet-monitor pings using HTTP which is on a different network layer. Your web application has to respond to it which explains the response time
