### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by moodhairboy** [CastawayLabs/cachet-monitor#49]
How do I resolve the issue below:

2016/12/21 11:15:14 /Users/m/p/gospace/src/github.com/castawaylabs/cachet-monitor/incident.go:36: cannot fetch component: Get https://localhost/api/v1/components/2: dial tcp [::1]:443: getsockopt: connection refused
2016/12/21 11:15:14 /Users/m/p/gospace/src/github.com/castawaylabs/cachet-monitor/monitor.go:200: Error sending incident: Post https://localhost/api/v1/incidents: dial tcp [::1]:443: getsockopt: connection refused

I am running cachetHQ in a docker container on a mac and the cachet-monitor app outside the docker container.

**Comment by matejkramny** [comment]
Make sure your cachet has https (and running on port 443).

> I am running cachetHQ in a docker container on a mac and the cachet-monitor app outside the docker container.

`cachet-monitor`'s `localhost` is different. You must set the IP address of the docker container or run `cachet-monitor` inside a linked container
