### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by moodhairboy** [CastawayLabs/cachet-monitor#52]
all,

I've managed to get cachet-monitor working, but when it attempts tp create incident I get the following errors"

2017/01/15 13:00:19 /Users/m/p/gospace/src/github.com/castawaylabs/cachet-monitor/incident.go:36: cannot fetch component: Get https://10.115.x.xxx/api/v1/components/12: dial tcp 10.115.4.102:443: getsockopt: connection refused
2017/01/15 13:00:19 /Users/m/p/gospace/src/github.com/castawaylabs/cachet-monitor/incident.go:36: cannot fetch component: Get https://10.115.x.xxx/api/v1/components/13: dial tcp 10.115.4.102:443: getsockopt: connection refused
2017/01/15 13:00:19 /Users/m/p/gospace/src/github.com/castawaylabs/cachet-monitor/monitor.go:200: Error sending incident: Post https://10.115.x.xxx/api/v1/incidents: dial tcp 10.115.4.102:443: getsockopt: connection refused
2017/01/15 13:00:19 /Users/m/p/gospace/src/github.com/castawaylabs/cachet-monitor/monitor.go:200: Error sending incident: Post https://10.115.x.xxx/api/v1/incidents: dial tcp 10.115.4.102:443: getsockopt: connection refused

The monitor continues running and then when it tries to write an incident the same errors occur.

Searching google pulls up more confusion than clarity - is this a port access issue on the server running cachet?

**Comment by craftbyte** [comment]
seems like you are trying to connect to an https port, are you sure you are running https and there is no firewall between the monitor and the cachet installation?

**Comment by matejkramny** [comment]
👍 @craftbyte 

Please check your cachet installation
