### ISSUE TITLE
Quick question about the timeout config...

### ISSUE THREAD

**Issue by haydenjames** [CastawayLabs/cachet-monitor#53]
Here's my current config:

```
`{
  "api_url": "http://status.mysite.com/api/v1",
  "api_token": "xxxxx",
  "insecure_api": true,
  "monitors": [
    {
      "name": "mysite",
      "url":  "http://mysite.com/ping",
      "threshold": 80,
      "component_id": 3,
      "metric_id": 4,
      "interval": 30,
      "timeout": 25,
      "expected_status_code": 200
    }
  ]
}
```

If I set "timeout": 60, instead of 25. Will that overlap (interval is 30) cause issues with monitor? Will it wait for that check to timeout until next check or will the interval of 30 reset?

For my timeout I would like 60 seconds but when I set interval to 120 and set cacht's:
"How many minutes of threshold between metric point?" to 5

The graph still shows 1 min intervals. The metric never obey the minute setting of 300 seconds. 

So Hoping to use 30 second interval and longer timeout. 

Possible?

**Comment by matejkramny** [comment]
It's not possible to have a timeout which is greater than the interval.

The metrics may be a cachet bug.
