### ISSUE TITLE
Cachet-Monitor as a Windows Service?

### ISSUE THREAD

**Issue by Mikagami** [CastawayLabs/cachet-monitor#54]
I have cachet-monitor running on a windows server box and was wondering if someone has any idea on how to have cachet-monitor run as a windows service? Anyone else install it in a windows environment?

**Comment by matejkramny** [comment]
`cachet-monitor` is a binary file. Unfortunately, I have no experience on Windows. If anyone is able to help I can add this to the installation documents

**Comment by Mikagami** [comment]
I hope someone can help. At the moment I run the app via the command `cachet-monitor [config file]` but since I am running this from a remote machine, as soon as I disconnect from the session the app stops running.

**Comment by matejkramny** [comment]
on linux i usually run `supervisor` or `monit`.

You can try this on windows as it's python: https://stackoverflow.com/questions/7629813/is-there-windows-analog-to-supervisord

Also: https://support.microsoft.com/en-us/help/137890/how-to-create-a-user-defined-service

**Comment by Mikagami** [comment]
Thank You Matej. The second link you provided alongside the one below, which helped me pass on parameters, was what gave me the solution I wanted.
[http://www.timdavis.com.au/general/creating-a-user-defined-service-in-windows-7](url)
