### ISSUE TITLE
ICMP Test?

### ISSUE THREAD

**Issue by Mikagami** [CastawayLabs/cachet-monitor#55]
I know that cachet-monitor can ping URL but I would like to use this to also check if an actual device is responding. Is it possible with cachet-monitor and I am just missing something in the config file? Even better would be specifying a port as well...

**Comment by matejkramny** [comment]
Do you mean if it responds to ICMP requests?

**Comment by Mikagami** [comment]
Yeah, sorry about that. I did mean ICMP.

**Comment by matejkramny** [comment]
Don't think that currently works, though you can try with the tcp test.

Something should be developed though

**Comment by matejkramny** [comment]
dup #38
