### ISSUE TITLE
Having an issue with creating monitor config as Ubuntu service

### ISSUE THREAD

**Issue by jaxonashton** [CastawayLabs/cachet-monitor#64]
Getting an error of 

```[/etc/systemd/system/cachet-monitor.service:15] Executable path is not absolute, ignoring: cachet-monitor -c /root/cachet-config.yaml
Mar 10 17:11:47 CachetMonitor systemd[1]: cachet-monitor.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

when executing `service cachet-monitor status`. I can't seem to figure this out as I can run the script manually with no issues with `cachet-monitor -c /root/cachet-config.yaml`, but when it comes to creating it as a service, it's not cooperating.

Looking for any help that can be provided.

**Comment by matejkramny** [comment]
Bizarre, there is an `ExecStart` directive. What system are you running on?

**Comment by jaxonashton** [comment]
I was able to get this figured out. It appears that it didn't like the absolute path I was using in the `ExecStart` directive. Updating this to `ExecStart=/usr/local/bin/cachet-monitor -c /root/cachet-config.yaml` fixed the issue.
