### ISSUE TITLE
Init script

### ISSUE THREAD

**Issue by ozzy-simpson** [CastawayLabs/cachet-monitor#65]
I'm an Ubuntu noob, so forgive me.  Is there an upstart script for 14.04?  The systemd one provided only works with 15 and up (I believe).

**Comment by ozzy-simpson** [comment]
Nevermind, I figured it out myself!  Here's the code if anyone needs it.  Add it to `/etc/init/cachetmonitor.conf`, shutdown your server, and boot it up again - it should work.

```
description "Cachet Monitor"

start on startup

env USER=root
env HOME=/root

setuid root
setgid root
chdir /root

script
    exec cachet-monitor -c /cachet-monitor.json --immediate
end script
```

**Comment by coffeverton** [comment]
Hi, where did you put the cachet-monitor executable?
In /root?
