### ISSUE TITLE
Better Instructions for Install

### ISSUE THREAD

**Issue by thewillwilson** [CastawayLabs/cachet-monitor#69]
Write better instructions for installs, not just install binaries.

**Comment by jvanst** [comment]
I'm not sure what other information is needed, what operating system are you trying to install on? 

If you are new to Linux and trying to run this on a headless server, copy the link from the release page which suits your system. Then download and run with the following:

`wget https://github.com/CastawayLabs/cachet-monitor/releases/download/v3.0/your_release_package`

`chmod +x your_release_package`

`./your_release_package`

**Comment by thewillwilson** [comment]
I was just being stupid ¯\_(ツ)_/¯
