### ISSUE TITLE
OSX installation

### ISSUE THREAD

**Issue by razuro** [CastawayLabs/cachet-monitor#82]
**OS version: 10.13 (High Sierra)**
**GO version: go version go1.9.1 darwin/amd64**
**cachet-monitor version: 3.0 - cachet_monitor_darwin_amd64**

When I try running `./cachet-monitor` it says `-bash: ./cachet-monitor: Permission denied`

I'm able to build and run hello world program here: https://golang.org/doc/install#testing

Please let me know what I've missed.

Thanks!

**Comment by matejkramny** [comment]
hi, you may be missing the execute permission on the file.

To fix this, simply run: `chmod +x ./cachet-monitor` and then try to execute the file again

**Comment by razuro** [comment]
@matejkramny Thanks! That solves the issue 👍
