### ISSUE TITLE
Detailed installation guide?

### ISSUE THREAD

**Issue by eqMFqfFd** [CastawayLabs/cachet-monitor#86]

**Comment by kenygamer** [comment]
I have a server running Linux Ubuntu 16.04.3 LTS, what do I have to do step by step?

**Comment by gabrielepmattia** [comment]
Maybe I can help you

1. Download **cachet_monitor_linux_386** (or **cachet_monitor_linux_amd64** if your are sure that you have an x64 machine)
2. Rename the file to `cachet_monitor` with `mv` command
3. Make the file executable with `$ sudo chmod +x cachet_monitor`
4. Put the executable in a PATH directory so you can access it directly via terminal, I suggest you `/usr/local/bin`
5. Create a `config.yaml` file by starting with one suggested in the readme (You can find the api `token` in the Cachet dashboard in your profile page by clicking to your username)
6. Now test your configuration with `$ cachet_monitor -c config.yaml`
7. If everything works as expected use `nohup` or for example `supervisord` to make the program autostart at the system boot

**Comment by eqMFqfFd** [comment]
@gabry3795  x84 (64 bits ) not x64

**Comment by Hendrik44** [comment]
How i can install and use it in a docker setup/enviroment?

**Comment by Herz3h** [comment]
Would be nice to have instructions or a config file to make it docker ready.
